#pragma once

#include <algorithm>
#include <array>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <cinttypes>
#include <climits>
#include <cmath>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <queue>
#include <random>
#include <set>
#include <shared_mutex>
#include <source_location>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <thread>
#include <tuple>
#include <type_traits>
#include <typeinfo>
#include <unordered_map>
#include <variant>
#include <vector>

/*
#include <boost/asio/awaitable.hpp>
*/

#include <QApplication>
#include <QColor>
#include <QDateTime>
#include <QDebug>
#include <QEvent>
#include <QGeoCircle>
#include <QGeoCoordinate>
#include <QGeoPath>
#include <QGeoPolygon>
#include <QGeoRectangle>
#include <QImage>
#include <QJsonDocument>
#include <QMetaProperty>
#include <QObject>
#include <QPainter>
#include <QPoint>
#include <QQuickFramebufferObject>
#include <QStandardPaths>
#include <QString>
#include <QThread>
#include <QTime>
#include <QTimer>
#include <QTranslator>
#include <QVariant>
#include <QVariantList>
